site_name: SELinux
nav:
  - Programme: 'index.md'
  - Introduction et troubleshooting: 'TP1.md'
  - Gestion de la politique SELinux: 'TP2.md'
  - Création de module custom: 'TP3.md'
  - MLS/MCS: 'TP4.md'
  - SELinux et conteneurs: 'TP5.md'
  # - SELinux cheatsheet: 'cheatsheet.md'
# Theme material
theme:
  name: "material"
  language: "fr"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  icon:
    edit: fontawesome/regular/pen-to-square
    repo: simple/gitea
    annotation: material/eye-circle
  palette:
    scheme: slate
    primary: "cyan"
    accent: "cyan"
  features:
    - content.action.edit
    - search.highlight
    - search.suggest
    - navigation.top
    - content.code.copy
    # - navigation.sections
    # - navigation.indexes
    # - navigation.tracking
    # - navigation.path
  highlightjs: true
  hljs_languages:
    - yaml
    - django
    - nginx
    - console
    - properties
    - shell

# Extensions
markdown_extensions:
  - toc:
  - admonition
  - codehilite
  - footnotes
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Plugins
plugins:
  - material/social:
      cards_layout: default/variant
      cards_layout_options:
        background_color: "#0b1329"
        font_family: VT323
  - search:
      separator: '[\s\-\.]+'
      lang:
        - fr

# Customization
extra_css:
  - stylesheets/extra.css
